### ISSUE TITLE
Let main.py accept filename as an argument

### ISSUE THREAD

**Issue by lonesword** [aerospaceresearch/orbitdeterminator#100]
Right now `orbit.csv` is hardcoded inside main.py. It would be more convenient if we can supply the filename as a command line argument

**Comment by petioptrv** [comment]
I will take a crack at this

**Comment by lonesword** [comment]
@petioptrv [Argparse](https://docs.python.org/3/library/argparse.html) is a very easy way to do this. Hardly 4 lines I guess. Please assign the issue to yourself.

**Comment by petioptrv** [comment]
Here is the pull request for this issue #101

**Comment by Alexandros23Kazantzidis** [comment]
First of all thank you very much for the contribution
Yes, it is a good observation I will check the pull request and also we need to wait for @Nilesh4145  to check the new code also.
