### ISSUE TITLE
Add a .gitignore file

### ISSUE THREAD

**Issue by aryadas98** [aerospaceresearch/orbitdeterminator#107]
A `.gitignore` file is needed to ignore `__pycache__` files. These are machine dependent files and should not be here in the main repo.

`orbitdeterminator/filtered.csv` is the output of an execution and should be ignored too.

**Comment by Nilesh4145** [comment]
Hello @aryadas98 We appreciate your suggestions. This project was actually done by 2 people, me and @Alexandros23Kazantzidis . He was a little unfamiliar with these conventions, so he might have missed it at some places. Regarding filtered.csv, it has been purposely kept there for people to have an idea of how the outputs look like even if they have issues executing the code.
We'll appreciate if you could look for more errors and open a pull request.

**Comment by Alexandros23Kazantzidis** [comment]
Yeah for __pycache__ a .gitgnore should be added also for idea folders too which PyCharm constantly creates. I will add it since we all agree on that. For the filtered.csv I agree with Nilesh, we want it to be there so that people can see what the output format of the filtering is.

**Comment by aryadas98** [comment]
No problem, I am new too! Good to meet you all. :-D
