### ISSUE TITLE
Jorge_dev This branch is 95 commits ahead, 73 commits behind master.

### ISSUE THREAD

**Issue by Alexandros23Kazantzidis** [aerospaceresearch/orbitdeterminator#132]
Hey @PerezHz I was watching your branch really cool stuff you have there, but I can see that your branch is a bit complex. I hope you will be able to merge it without any troubles but I doubt it. When you try to do it we should all help you so that we can ensure the process will be smooth.

**Comment by PerezHz** [comment]
I mean, at least for now the issue of keeping my dev branch up to date wrt current master seems to be solved.. When the code in my dev branch starts to interact with the rest of the code, then I'll surely need your help guys! Before merging, are there any other specifics that I should take care of?

**Comment by Alexandros23Kazantzidis** [comment]
If the rebase went smoothly then I think you can try to merge. But I think you will get lots of conflicts if you were working on the scripts that also other students were working. @Nilesh4145  @aryadas98  @aakash525  Guys if you can also share your opinion on this matter.

To add your new dependencies you will need to add them to requirements.txt (with a pip freeze > requirements.txt of your local environment - do that only if you have a separate local environment only for working on this project). Then we will also have to update the setup.py to take all the dependencies from the requirements.txt

**Comment by aryadas98** [comment]
The branch has been merged now! :tada:
