### ISSUE TITLE
Put all sample data in one folder

### ISSUE THREAD

**Issue by aryadas98** [aerospaceresearch/orbitdeterminator#156]
Right now all the sample data used for testing (.csv files) are scattered across the whole repo. Put all of them in `example_data`. Do not mess with any script specific files - like `main.py` runs with `orbit.csv` by default, so don't move it. Check the same for automated and propagation folders. In the end, delete any empty folders.

**Comment by vidhanarya** [comment]
Any CSV file not in use by any script is already in example_data? Files in dst folder are generated by the automated.py script so unless we change input and output parameter of the scripts I guess the state of the codebase will remain same. Please confirm if I am right or not

**Comment by aryadas98** [comment]
Yes, you are correct. I will have to ask others about it first.

**Comment by CooperPair** [comment]
So what's wrong in putting datasets in a folder as it will look more structured and for this, we just need to change the path of datasets in files?

**Comment by aakash525** [comment]
Obviously, for managing database, you have to put the dataset in a single folder (create sub-folder if required) and after this, you have to update the path of datasets in respective files.

**Comment by vidhanarya** [comment]
Solved in PR #157, this issue can be closed now
