### ISSUE TITLE
An error was found, but returning just with the version: No module named 'termios'

### ISSUE THREAD

**Issue by Umbrstell** [aerospaceresearch/orbitdeterminator#179]
pytest is ok ,but when I run main.py  An error was found, but returning just with the version: No module named 'termios'    

C:\Users\astronomy\PycharmProjects\untitled1\orbitdeterminator\orbitdeterminator>python main.py -f \Users\astronomy\PycharmProjects\untitled1\orbitdeterminator\orbitdeterminator\orbit.csv
An error was found, but returning just with the version: No module named 'termios'

************Welcome To OrbitDeterminator************

Workflow for OrbitDeterminator is as follows:

                   -----------    ----------------------
Positional data--->| Filters |--->| Keplerian elements |--->Determined Orbit
                   |         |    | Determination      |
                   -----------    ----------------------

Available filters:               | Available methods for orbit determination:
  1. Savitzky Golay Filter       |   1. Lamberts Kalman
  2. Triple Moving Average Filter|   2. Cubic spline interpolation
                                 |   3. Ellipse Bset Fit
                                 |   4. Gibbs 3 Vector

***********Choose filter(s) in desired order of application***********
(SPACE to toggle, UP/DOWN to navigate, RIGHT/LEFT to select/deselect and ENTER to submit)
*if nothing is selected, Triple Moving Average followed by Savitzky Golay will be applied
Traceback (most recent call last):
  File "main.py", line 222, in <module>
    process(args.file_path, args.error, args.units)
  File "main.py", line 41, in process
    inquirer.Checkbox('filter',
AttributeError: module 'inquirer' has no attribute 'Checkbox'

**Comment by Umbrstell** [comment]
An error was found, but returning just with the version: No module named 'termios'

**Comment by Curious-Nikhil** [comment]
Hi,

For this error `AttributeError: module 'inquirer' has no attribute 'Checkbox'`
Unfortunately, `Inquirer `which is based on `blessing` module is not supported by windows.  

[PyInquirer](https://github.com/CITGuru/PyInquirer) is a better alternative with similar features. 

I tried installing PyInquirer with the current requirements of OD and I get a `regex build fail error` which is due to outdated C++ build tool version. Updating the build tools doesn't help either.

**Comment by hornig** [comment]
hmmm, i cannot replicate this.
on my windows 10 version of inquirer it works so far.
is that still a thing?
