### ISSUE TITLE
Math Domain Error

### ISSUE THREAD

**Issue by archithadge** [aerospaceresearch/orbitdeterminator#183]
``Traceback (most recent call last):
  File "main.py", line 222, in <module>
    process(args.file_path, args.error, args.units)
  File "main.py", line 106, in process
    kep_final_inter[6, 0] = sgp4.rev_per_day(kep_final_inter[0, 0])
  File "/home/archit/test/orbitdeterminator/orbitdeterminator/propagation/sgp4.py", line 30, in rev_per_day
    t = 2*pi*math.sqrt(axis**3/meu)
ValueError: math domain error
``
I am encountering this issue when I run main.py select any of the filters and methods.

**Comment by archithadge** [comment]
Tried to solve this issue here #182 .

**Comment by vidhanarya** [comment]
Solved in #182
