### ISSUE TITLE
Pykep V2.1 is not available 

### ISSUE THREAD

**Issue by Curious-Nikhil** [aerospaceresearch/orbitdeterminator#187]
Hi,
Installing(Win OS) pykep v1.2 returns a PackageNotFounderror
`conda install pykep==2.1
`

![image](https://user-images.githubusercontent.com/12347532/76135026-3c5f9e80-6049-11ea-9ddb-043b6aeb37d0.png)

**Available versions:**
![image](https://user-images.githubusercontent.com/12347532/76134947-87c57d00-6048-11ea-8f27-76cefaaddcf8.png)

Installing the latest pykep (v2.4.x), **resets** my python env to 3.8.x, which isn't supported by Orbit Determinator.
Thanks.

**Comment by AhmedEHaddad** [comment]
Have you tried downloading the 1.2 version from archives

**Comment by Curious-Nikhil** [comment]
> Have you tried downloading the 1.2 version from archives

I can't find it on [conda-forge](https://anaconda.org/conda-forge/pykep/files?version=2.1). 

![image](https://user-images.githubusercontent.com/12347532/76309118-1b6da680-62f2-11ea-9a73-0ef572010b29.png)

**Comment by KUEE1080** [comment]
I am not sure if this is an appropriate way, but I had the same issue and resolved it by using 

pip install pykep==2.1

**Comment by Curious-Nikhil** [comment]
> I am not sure if this is an appropriate way, but I had the same issue and resolved it by using
> 
> pip install pykep==2.1

![image](https://user-images.githubusercontent.com/12347532/77090667-7e1b1c80-6a2d-11ea-8cc9-f001bf534ace.png)

Yes, I can confirm that the `pip install` command works. Surprisingly conda lib doesn't have pykep 2.1 version. 

Best to use `conda install pykep==2.1`  in linux. 
Thanks 👍

**Comment by hornig** [comment]
@Curious-Nikhil what do you think about this solution? https://github.com/aerospaceresearch/orbitdeterminator/pull/238
