### ISSUE TITLE
pykep package not getting installed

### ISSUE THREAD

**Issue by Avhijit-codeboy** [aerospaceresearch/orbitdeterminator#229]
Conda is not able to find the pykep package
![error](https://user-images.githubusercontent.com/41890388/111254357-de41a000-863a-11eb-842d-719dc732cbc8.png)

**Comment by Avhijit-codeboy** [comment]
I resolved it. 
Use Conda forge channel to install pykep and it will work.
`conda install -c conda-forge/label/cf202003 pykep`

**Comment by hornig** [comment]
@Avhijit-codeboy I replaced the pykep function with our own one. If you want, you can check here https://github.com/aerospaceresearch/orbitdeterminator/pull/238
