### ISSUE TITLE
No module named 'lamberts_method'

### ISSUE THREAD

**Issue by AlexanderEvitt** [aerospaceresearch/orbitdeterminator#231]
I install following the methods described in the instructions as best as I can (using python 3.6.5 because pykep won't install with conda below python==3.6). I run the following code:
`from orbitdeterminator.kep_determination.gauss_method import gauss_method_mpc`
And receive the following error:
![image](https://user-images.githubusercontent.com/50218791/111856374-9b185300-8900-11eb-927e-94187d72fb72.png)
I'm not really sure what's happening here. It looks like this import is failing but I've verified that all the files for the package are installed correctly, including the one labelled lamberts_method.py. 
Any idea what's happening here, and what the possible workarounds might be?

**Comment by deoudit** [comment]
You need to install the package called lamberts from here https://pypi.org/project/lambert/.

**Comment by hornig** [comment]
> You need to install the package called lamberts from here https://pypi.org/project/lambert/.

Hi, that is actually not true ;). That is our lamberts_method.py

**Comment by hornig** [comment]
hi,
i am not sure I understand this issue. for me it works and also the lamberts_method is there. do you have a link (github link) to the line of the code where this is?

**Comment by KingShark1** [comment]
i worked all issues like this by just updating the __init__.py in every folder, and using relative imports, absolute imports tend to fail on different machines.
@hornig i think this issue should be closed now, there is no problem with the existing code, this particular issue is on the machine used by @AlexanderEvitt .
